// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCteIvuVInYHZyi0YxTepNf53RX1h6Kw3w',
    appId: '1:49058563383:web:bb94f2448f8aa627bf86b2',
    messagingSenderId: '49058563383',
    projectId: 'baticraftmobile',
    authDomain: 'baticraftmobile.firebaseapp.com',
    storageBucket: 'baticraftmobile.appspot.com',
    measurementId: 'G-9EH72Q5TST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvcUl-YE2Bgv05mJJ-EJqLMgk9TJizq1A',
    appId: '1:49058563383:android:a0ac44a9192071f6bf86b2',
    messagingSenderId: '49058563383',
    projectId: 'baticraftmobile',
    storageBucket: 'baticraftmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSb0iV1L5QnANDnr_bb2ChFkJfZ9MYxc',
    appId: '1:49058563383:ios:df602879cd99451fbf86b2',
    messagingSenderId: '49058563383',
    projectId: 'baticraftmobile',
    storageBucket: 'baticraftmobile.appspot.com',
    androidClientId: '49058563383-79nbd1r25kh0lutjbjrm55dlv28c9d79.apps.googleusercontent.com',
    iosBundleId: 'com.example.baticraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSb0iV1L5QnANDnr_bb2ChFkJfZ9MYxc',
    appId: '1:49058563383:ios:248a5e085a242c9cbf86b2',
    messagingSenderId: '49058563383',
    projectId: 'baticraftmobile',
    storageBucket: 'baticraftmobile.appspot.com',
    androidClientId: '49058563383-79nbd1r25kh0lutjbjrm55dlv28c9d79.apps.googleusercontent.com',
    iosBundleId: 'com.example.baticraft.RunnerTests',
  );
}
