name: baticraft
description: "Project A1 Semester 4"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  path_provider: ^2.0.9
  equatable: ^2.0.3
  google_sign_in: ^6.2.1
  provider: ^6.1.1

  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  fluttericon: ^2.0.0
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  flutter_sticky_header: ^0.6.0
  http: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  get: ^4.6.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  image_picker: ^0.8.3+3
  flutter_date_picker: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons8-google-480.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo-Regular.ttf
        - asset: assets/fonts/Arvo-Bold.ttf
        - asset: assets/fonts/Arvo-BoldItalic.ttf
        - asset: assets/fonts/Arvo-Italic.ttf
          weight: 700

    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
          weight: 700
# flutter_icons:
#   remove_alpha_ios: true
#   android: true
#   ios: true
#   image_path: "assets/images/logoapps.png"
